### ISSUE TITLE
Intermittent tunnel to nowhere

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#100]
TERRAN3, Sect 94,78. Sometimes works correctly, sometimes teleported to an empty spot on the map.

**Comment by WDLmaster** [comment]
Hmm, I'm almost sure this is no bug. The tunnel you mentioned (and this setup can be found in other levels, too, like all MINE.LVLs) has 2 tunnels share their entrances and exits on the same cell. So TRCL might get confused when you exit a tunnel but, because you're over the entrance of another tunnel, it tries to immediately enter the other tunnel again.

That's why I said (over a year ago) that tunnel entering should only triggered at collision and not by measuring the distance. Of course, you could simply use the direction that you face when approaching the tunnel. When the player points AWAY from the surface, it cannot count as "entering a tunnel" … etc …

**Comment by cjritola** [comment]
Fortunately the engine does use ground-collision to propose entrance (org.jtrfp.trcl.beh.CollidesWithTerrain:117) and the lookup hashmap is strictly for entrances only (org.jtrfp.trcl.flow.Mission:691).

The tunnel-to-nowhere is strange in that it seems to be doing half the job by moving the player but not the part of changing root grids and they are in the same block of code. This smells like an uncaught exception triggering escape from program flow.

**Comment by WDLmaster** [comment]
"Fortunately the engine does use ground-collision to propose entrance"

… And I though I had the answer ;-)
