### ISSUE TITLE
Projectile velocity should be sum of projector velocity and default speed

### ISSUE THREAD

**Issue by StrikerMan780** [jtrfp/terminal-recall#105]
While digging through Fury3, I found that not only is there a Set speed for specific weapons when firing lasers, the speed of the player is added to the laser being fired. That's why the lasers seem ungodly slow right now. It's also why in the original, the lasers seemed to be moving the same speed in relation to you regardless of your throttle.

The formula is roughly like this:

Projectile Velocity X = (float) Ship Velocity X
Projectile Velocity Y = (float) Ship Velocity Y
Projectile Velocity Z = (float) Ship Velocity Z
Speed = sqrt(pvx * pvx + pvy * pvy + pvz * pvz);
Base Speed = (int) Speed

Then:
firelaser(...etc Laser Speed + Base Speed)

**Comment by TheTrustedComputer** [comment]
Yes, I experienced this as well. However, this does not apply when the ship has invisibility; even more so, it is also stated in the Fury3 help file too!

**Comment by StrikerMan780** [comment]
I think you replied to the wrong issue.

**Comment by WDLmaster** [comment]
No, the player's speed is NOT added to the projectile velocities in the original game. Unless you have a version that's different from mine. We had this discussion a few days back and the actual reason for it being too slow is 1) the player moves way too fast in TRCL, 2) the huge view distance gives an even more extreme perception of slowness and 3) the FOV in TRCL is too low.

I did a test by measuring a flying PAC projectile 9 times. 3 times when standing still, 3 times moving slow, 3 times moving fast. The projectile speed are always the same, ignoring the tiny fluctuation of 0.000467 % that's caused by heavy frame rate fluctuations in the original game:

* Standing still:
2359280
2359277
2359278

* Moving slow:
2359283
2359276
2359281

* Moving fast:
2359270
2359271
2359258

The faster the game runs the lower these numbers but they're still the "same"…

**Comment by TheTrustedComputer** [comment]
My reply is relevant enough...

**Comment by StrikerMan780** [comment]
No it isn't, this is about projectile speed, not tunnel entrances and exits.

**Comment by TheTrustedComputer** [comment]
Look, l'm trying to not ruin the project, nor to make things hard for you guys. I'm making a connection that this issue does not apply with invisibility, and how it does to tunnels.

I do know the weapon velocity is fixed when I went testing Terminal Recall. As a result, this could be a great challenge when it comes to taking down enemy aircraft all around the player, so maybe this might help you clarify things a bit. Sorry for any confusion, I was making a connection of two similar things!

**Comment by StrikerMan780** [comment]
I was just saying how that should be in it's own report. There is no connection between the two and no need to confuse the developer.

**Comment by WDLmaster** [comment]
Oh, I didn't know that you have the source code (how could I possibly know). So far, we always relied on some half assed observations or examining the RAM content and what not. So how about sharing a few critical numbers like all weapon speeds, weapon damages, intervals, explosion sizes, explosion lifespans and stuff like that.

And while you're at it: I would like to know what is written to offset 116776 to 118595 of the savestate files because that's the only block that's unknown so far and it's always zero as far as I'm aware.

**Comment by StrikerMan780** [comment]
The damages and speeds are as follows:

Damage | Speed
------------ | -------------
SKL - 4096 | 0x200000
RFL20 - 4096 | 0x400000
DOM - 16834 | 0x400000
VIP - 32768 | 0x400000
BFM - 65536 | 0x400000

**Comment by WDLmaster** [comment]
Maybe because missiles linearly accelerate from a slower (524288 (0x80000)) to a faster (4194304 (0x400000)) velocity within one second.
