### ISSUE TITLE
Unreliable collision detection between player and DEFObjects

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#119]
It appears that collisions between Player and DEFObjects is incorrectly assuming the DEFObject to be a infinitesimal point whereas the Player has a collision radius.

**Comment by WDLmaster** [comment]
Does TRCL use the collision radius given in the DEF block or do you calculate it from the outermost vertices? If the former, it explains why the collision detection does not work in my test level (and ONLY with my test level). All the original levels work with collision detection in TRCL. My DEFs simply have a "0" as collision radius because the original game ignores it and always calculates it from the outer most vertices on level load.

**Comment by cjritola** [comment]
Yes, it did use the DEF radii; my error. Missed the part where the spec is not to spec. (:

Player/DEF collisions are now based roughly on Model dimensions using a cylindrical boundary. It's not perfect but should be sharply improved.

Also some details had to be synthesized for hit points on a collision: It is currently set at 8024 every 250 ms which seems roughly on-par with the original game. This will result in delayed destruction of heavily-armored DEF objects. Example: Fly into a building in TERRAN; no immediate results but eventually the building will "die" as 8024 damage is delivered at a rate of 4HZ.

**Comment by WDLmaster** [comment]
Ok, that means the lack of collision detection in the test level(s) was expected behavior (because all my DEF radii were set to zero) and not a bug. 

Yeah, I think anything other than the original hitbox shape is an improvement. I'm not entirely sure but it looks like the original game uses an axis aligned bounding box and initially I thought it's always cube-shaped, no matter what the real dimensions are – but it's not. It kinda depends on the logic an object uses. Static (ground) objects seem to match the real dimensions but it's still axis aligned. Air enemies have an enlarged hitbox (kind of) to better be able to hit them when moving. The only cube-shaped bounding boxes are the user defined ones, which, by the way, I use to effectively disable collision detection by setting the number of hitboxes to "1" an leave the size at "0" (used for trees which I don't want to be destroyed, hehe).
