### ISSUE TITLE
Failure to run on GeForce 9800 GT

### ISSUE THREAD

**Issue by mrjoshua23** [jtrfp/terminal-recall#123]
I need help
![image](https://cloud.githubusercontent.com/assets/15824644/11455054/400510ac-9617-11e5-9d9d-630a0177ae15.png)

**Comment by cjritola** [comment]
Does this issue repeat when you try to start again?

Can you post the output of log.html (it should have been written to the same folder as RunMe.jar). If this was a pre-built .JAR from Google Code it won't be there.

In case it is a pre-built .JAR, Terminal Recall should build it from github instructions instead as the prebuilt is *very* old.

**Comment by mrjoshua23** [comment]
http://pastebin.com/bQ3NVrmS

**Comment by mrjoshua23** [comment]
i built it from the github instructions

**Comment by cjritola** [comment]
I may have found the problem. The most recent commit may fix this issue; it would be great if you could update to latest and confirm.

In the supplied log.html was an INVALID_VALUE error from GL during glTexStorage*. It could not be made sense as to why why INVALID_VALUE should be thrown when it works on other hardware. Researching glTexStorage*D showed official support only in GL 4.2+, though it has de-facto support in previous implementations.

Your configuration is unique in that its GL support maxes out at 3.3, which makes it an excellent test case. There was a non-neligible probability that glTexStorage*D is not supported by your card and/or drivers. Terminal Recall is meant to work with 3.3 cards so the recent commit changes those glTexStorage*D calls to glTexImage*D, which has been supported since GL 1.0. 

This should hopefully fix the problem. If not, it likely is going to uncover more problems down the road, we will see.

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11459429/5c50d2ea-96a4-11e5-8faf-924d3ec25402.png)

nope still black screen, i did the instructions again pulled 462 modules, and it still didnt work, is there a good known version of terminal recall i can play with?

**Comment by mrjoshua23** [comment]
http://pastebin.com/DwAyCKqk

**Comment by cjritola** [comment]
Thanks for the log; made another attempt at fix. There's going to become guesswork because the error reported by the driver is vague.

I am not sure if there is a previous revision which would work for you because I have not seen any other cases with the error you are getting.

**Comment by mrjoshua23** [comment]
hey this is my first git hub project working, eh first timer noob whatcha call it

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11461228/f4b68296-96cc-11e5-967b-b4ef6c45785d.png)
im not having any good vibes, and im on a different pc, my laptop do you want specs?

http://pastebin.com/rjCa2Qhp

**Comment by cjritola** [comment]
Welcome to GitHub :D  

When re-running `mvn clean install`, `java -jar RunMe.jar` etc is it working now?

**Comment by cjritola** [comment]
Welcome to GitHub :D  

Bugs like these sometimes take a bit of back-and-forth since hardware can be very unique and keeps me from testing it on my own.

No need for specs on that other machine; the log says it probably can't run Terminal Recalll. The previous machine is a better bet. Did you try re-running `mvn clean install` and `java -jar RunMe.jar` after I uploaded those last changes yesterday?

**Comment by mrjoshua23** [comment]
yea i did a git pull and still black screen am i just unlucky?

**Comment by cjritola** [comment]
No, not unlucky; something's still awry. Can you provide the latest log.html from the original computer?

**Comment by mrjoshua23** [comment]
can you wait until wed night?

**Comment by cjritola** [comment]
Yes (:

**Comment by WDLmaster** [comment]
Contributing some more test cases:

After I saw that the GeForce 9800 is said to not support GL 3 (which I thought is impossible!) I re-activated a few of my old PCs lying around here catching dust for years. I can only test 2 of them at the moment, the others lack a PSU and I'm too lazy to switch them just to test TRCL. Both of them running Win7, both 64-bit, both GeForces, newest drivers just for TRCL tests. But their hardware is kinda messed up because I switched stuff from different PCs around and combined old RAM modules of different speeds and sizes etc. Anyway, to my surprise, both graphic cards have the black screen issue:

* The first one is a GeForce 8800 GTS (512 MB VRAM) from around October 2007 if I'm not mistaken. The CPU is some AMD with 3.1 GHz. Log: http://wdlmaster.de/TRCL/log18.html

* The second one is a GeForce 9600 GT (also 512 MB VRAM) from 2009 or so. CPU is an AMD Athlon 4000+ @ 2.41 GHz. RAM: 3.00 GB. The only thing to note here is the super slow 120 GB HDD from 2004 which causes the mvn clean install to take over a minute :-D Log: http://wdlmaster.de/TRCL/log19.html

One of the other PCs has an ATI card. I can test it too if you want after installing a PSU. From the top of my head I can't remember any hardware details but it's roughly 2010-tech. It also runs Win7 x64.

**Comment by mrjoshua23** [comment]
all this for wanting to play terminal velocity and fury 3 source
ports, geez i didnt mean to make more work for you

**Comment by cjritola** [comment]
@WDLmaster Thanks for those tests; there's definitely something funny going on with those cards. I checked the max specs for the 9600GT. TRCL allocates an array texture (3D texture) of 128x128x2048 for the codebook, the 9600 is supposed to be capable of up to 2048^3 and so should be within the card's ability. 

One thought was perhaps the codebook took too much space alongside the root buffer, etc. in a 512 card. Both of my cards are 1GB so I wouldn't notice. I imagine the OS takes up some VRAM too. The driver is *supposed* to perform swapping to system RAM as needed. Slightly skeptical I have been looking into measuring VRAM usage found here ( http://stackoverflow.com/questions/4552372/determining-available-video-memory ) but haven't gotten anything meanginful in terms of data.

Until a week ago I'd been using a very sluggish 160GB PATA for boot/swap in order to catch optimization problems but I just couldn't take it anymore.

**Comment by WDLmaster** [comment]
Yes, the low amount of VRAM came to my mind the moment I saw the black screen on the 9600. My every-day-card has 2 GB of VRAM so we both never experienced any running-out-of-VAM behavior.

I don't know how reliable the program "EVGA Precision" is but according to this program the VRAM consumption when launching TRCL is 755 MB. The initial value before launch was already at some 100 MB. I never shut down the system (only hibernation mode) so the VRAM and system RAM is already kinda messed up with stuff but it does not change the fact that TRCL apparently allocates 600+ MB of VRAM on launch.

After selecting New Game, the VRAM increases by another 140-ish MB and sits at around 890. The start of an actual level does not increase the VRAM much (just 5 MB or so). 

It might be a driver issue but after closing TRCL the VRAM goes not down to the initial 100-something but stays at nearly 300 …

**Comment by cjritola** [comment]
Those are sobering numbers. I got access to a GeForce 8400 GS 512MB and will try to get it working on there, then will report back here for 3rd party testing. @mrjoshua23 No need to try Terminal Recall on your computer yet (it probably won't work).

**Comment by WDLmaster** [comment]
I did not restart the test PCs after installing the new drivers yesterday. But now, after a restart, the black screen issue is partially gone. TRCL now renders the menu bar and all dialogs but the graphics are utterly, severely corrupted. The only thing not affected by this is the gray backdrop gradient in the main menu. Everything else consists of flashing, misplaced, distorted, scattered polygons. The white color is usually a sign of too low VRAM. The EVGA Precision program shows a VRAM consumption of 380 MB, 20 MB when TRCL is not running. Music plays fine so I guess at least those "audio textures" reside in VRAM (?) .

And I found another funny thing by accident, apparently only possible with onboard audio cards (which I never ever used, but the test PC has no "real" soundcard). The game crashes when no audio cable is plugged in. I thought I have seen enough strange things over the years but I was proven wrong. Kinda funny because it makes absolutely no sense at all. The log says the complete audio device was not found AKA there are no audio cards available on the system! But this could be a Windows 7 issue because it does not display the actual hardware name but the name of the output port names like "Headphones" or "Stereo-Speakers". And as I see it, TRCL uses the names reported by the system, not the driver.

**Comment by cjritola** [comment]
@WDLmaster  "Music plays fine so I guess at least those "audio textures" reside in VRAM (?) ." 
- Yes. And they literally are textures. (:

"The game crashes when no audio cable is plugged in. "
- Good catch. It sounds like TRCL doesn't handle the lack of soundcard gracefully. Probably a NullPointerException. I'll try disabling the onboard audio on my dev machine and see if I can catch it exploding.

**Comment by WDLmaster** [comment]
No no, it does not crash because no audio device is installed. It crashes because no audio cable was plugged in. Quite the difference.

**Comment by mrjoshua23** [comment]
well actually this is a learning experience for me too, cause now I
can use github to get others things and i know how it works! :)

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11542971/227b1664-9908-11e5-8d32-4dfa078042ab.png)

ok back on old pc or gaming pc, the other pc was my laptop, heres the results:

http://pastebin.com/VC9KcJMu

**Comment by cjritola** [comment]
Update: I am still working on fixing the issue; after some changes I am able to get it running on an 8400 but with garbage rendering. It is likely going to be a while before it will be ready for you to try again.

**Comment by mrjoshua23** [comment]
ok thanks, ive learned how to use git hub and got the quake 2 dos port working

**Comment by cjritola** [comment]
@mrjoshua23 Major GPU bugfix recently committed to Terminal Recall involving your GPU issue.

There is a good possibility it will work on a 9800 now. A verfification of this using the newest build at your easiest convenience would be great.

Technical details:
The driver version used in my tests is 340.96. Other versions may work too.
Performance will likely be *very slow*, with choppy sound, as it was on my test. It can be mitigated partly by shrinking the window.

This performance penalty is disproportionate to the core specs and shows heavy CPU usage. Furthermore, nVIDIA advertises the 9800 and 8400 as OpenGL 2.1 ( http://www.geforce.com/hardware/desktop-gpus/geforce-9800gt/specifications ), however the driver presents itself as 3.3 capable. ( http://stackoverflow.com/a/17358354/515655 ) It is possible that the driver is falling back to software rendering, which is very, very slow. This is a result of older hardware and surprisingly helpful driver design trying to make the program run, albeit poorly.

This would likely remain slow until I code up a lightweight renderer, which is in the plans for the moderate future.

**Comment by grrk-bzzt** [comment]
Hello,

The game doens't work on my GeForce GTX 970 under ArchLinux x86_64.
Here's the standard output
```
Overriding the default JVM settings. If you wish to manually set the JVM settings, include the `-Dorg.jtrfp.trcl.bypassConfigure=true` flag in the java command.
Restarting JVM with: 
	java -server -Dorg.jtrfp.trcl.bypassConfigure=true -Dcom.sun.management.jmxremote -XX:+UnlockExperimentalVMOptions -XX:+DoEscapeAnalysis -XX:+UseFastAccessorMethods -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:MaxGCPauseMillis=5 -XX:+AggressiveOpts -XX:+UseBiasedLocking -XX:+AlwaysPreTouch -XX:ParallelGCThreads=4 -Xms512m -Xmx512m -XX:+UseCompressedOops -XX:MaxDirectMemorySize=32m  -jar RunMe.jar STARTUP.POD FURY3.POD
			***TERMINAL RECALL***
	An unofficial enhancement engine for Terminal Velocity and Fury3.
	Copyright (c) 2012-2015 Chuck Ritola and contributors. See enclosed CREDITS file for details.
	Part of the Java Terminal Reality File Parsers Project.

		This program is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 3 of the License, or
	(at your option) any later version.
		This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.
   	You should have received a copy of the GNU General Public License
	along with this program; if not, write to the Free Software Foundation,
	Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

		THIS PROGRAM IS NOT SUPPORTED BY OR AFFILIATED WITH MICROSOFT OR TERMINAL REALITY INC.
	Bring any issues to the Terminal Recall GitHub page.
	www.jtrfp.org

CONTROLLER: net.java.games.input.LinuxCombinedController
Component found: A
Component found: B
Component found: X
Component found: Y
Component found: Left Thumb
Component found: Right Thumb
Component found: Select
Component found: Start
Component found: Mode
Component found: Left Thumb 3
Component found: Right Thumb 3
Component found: x
Component found: y
Component found: z
Component found: rx
Component found: ry
Component found: rz
Component found: pov
CONTROLLER: net.java.games.input.LinuxJoystickAbstractController
Component found: Stylus
Component found: x
Component found: y
Adding config tab: Control
Initializing graphics engine...
Setting up sound system...
SoundSystem: Active Driver Set To JavaSound Driver
SoundSystem: Active Device Set To null
setOutputByName null
SoundSystem: Active Output Set To null
Overriding null device to default...
...Done
SoundSystem: Active Device Set To default [default], version 4.2.5-1-zen
SoundSystem: Active Format Set To null
GLEventListener.init()
GPU info:
	Vendor: NVIDIA Corporation
	Renderer: GeForce GTX 970/PCIe/SSE2
	Ver: 4.3.0 NVIDIA 358.16
	GLSL: 4.30 NVIDIA via Cg compiler
System info:
	Vendor: Oracle Corporation
	Arch: amd64
	OS: Linux
	Ver:4.2.5-1-zen
SoundSystem: setting up textures...
...Done.
WindowClosing...
glExecutorThread.join()...
ThreadManager: WindowClosing Done.
```
And here's the error output
```
déc. 06, 2015 1:05:03 AM org.springframework.context.support.AbstractApplicationContext prepareRefresh
INFOS: Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@3b95a09c: startup date [Sun Dec 06 01:05:03 CET 2015]; root of context hierarchy
déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event0): Failed to open device /dev/input/event0 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event1): Failed to open device /dev/input/event1 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event10): Failed to open device /dev/input/event10 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event11): Failed to open device /dev/input/event11 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event12): Failed to open device /dev/input/event12 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event13): Failed to open device /dev/input/event13 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event14): Failed to open device /dev/input/event14 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event15): Failed to open device /dev/input/event15 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event16): Failed to open device /dev/input/event16 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event17): Failed to open device /dev/input/event17 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event18): Failed to open device /dev/input/event18 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event19): Failed to open device /dev/input/event19 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event2): Failed to open device /dev/input/event2 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event20): Failed to open device /dev/input/event20 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event21): Failed to open device /dev/input/event21 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event3): Failed to open device /dev/input/event3 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event4): Failed to open device /dev/input/event4 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event5): Failed to open device /dev/input/event5 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event6): Failed to open device /dev/input/event6 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event7): Failed to open device /dev/input/event7 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Failed to open device (/dev/input/event8): Failed to open device /dev/input/event8 (13)


déc. 06, 2015 1:05:04 AM net.java.games.input.ControllerEnvironment log
INFOS: Linux plugin claims to have found 2 controllers

FPSAnimator P1:Thread[main-FPSAWTAnimator-Timer0,5,main]: Task[thread Thread[main-FPSAWTAnimator-Timer0,5,main], stopped false, paused false shouldRun true, shouldStop false -- started true, animating true, paused false, drawable 1, drawablesEmpty false]
X11Util.Display: Shutdown (JVM shutdown: true, open (no close attempt): 1/1, reusable (open, marked uncloseable): 0, pending (open in creation order): 1)
X11Util: Open X11 Display Connections: 1
X11Util: Open[0]: NamedX11Display[:0.0, 0x7f4efc01af50, refCount 1, unCloseable false]
```

**Comment by cjritola** [comment]
Those messages are benign and should not stop it from running. Are you getting a black window? No window?

**Comment by grrk-bzzt** [comment]
A white window.

**Comment by cjritola** [comment]
It may have hanged. Does the issue repeat?

**Comment by grrk-bzzt** [comment]
It does every single time.

**Comment by cjritola** [comment]
@grrk-bzzt  Branched your issue to #125

**Comment by mrjoshua23** [comment]
what does branched your issue to #125 mean?

im on my laptop atm, again wed night i will try on my gaming pc, here is my laptop if it helps any

![image](https://cloud.githubusercontent.com/assets/15824644/11611461/2e4c6424-9b9d-11e5-9ad7-f7d6bbaf5f23.png)

http://pastebin.com/MuBi4wHp

**Comment by cjritola** [comment]
@mrjoshua23 I am treating GRRK's bug/reports as a separate issue, possibly unrelated to the one here, to keep this issue on-topic.

**Comment by cjritola** [comment]
Moved @WDLmaster's sound/crash issue to #126

**Comment by WDLmaster** [comment]
So, I tested the most recent TRCL again on the old 9600 GT and the 8800 GTS. The 8800 "runs" now but unimaginably slow (like you said). But on the 9600 I see no difference whatsoever. Looks still the same as before (black/white flickering polygons all over the place like said earlier in another post). Very strange because I actually expected it to be the other way around. The 9600 is newer and should have a better feature set 
…
…
…
theoretically.

**Comment by cjritola** [comment]
@WDLmaster Thanks for that info. Those might be important clues.

Asking the usual boilerplate question: 
Are the drivers on the 9600 up-to-date?

**Comment by mrjoshua23** [comment]
what does terminal recall look like when it works properly or at all?

**Comment by WDLmaster** [comment]
@cjritola

Of course the drivers are up to date on both test PCs (v341.92 for the 9600 GT) as stated in my first test report earlier. I was actually forced to update them because with the old ones TRCL crashed right away.

**Comment by cjritola** [comment]
@mrjoshua23 This is what to expect, though your title bar will be different in Windows:
![trcl-opening](https://cloud.githubusercontent.com/assets/1056698/11637896/2485f4b8-9cf2-11e5-9cff-decb175b4d3e.png)

**Comment by mrjoshua23** [comment]
oh great what am i doing wrong

**Comment by mrjoshua23** [comment]
[image: Inline image 1]

ok tried again using git pull and still this, this is on my gaming pc btw...

http://pastebin.com/EuU382ES

**Comment by WDLmaster** [comment]
@mrjoshua23

I just wanted to say the game runs fine on one of my test PCs which has a 9600 GT. You have a 9800 so it should (theoretically) run in any case. Say, do you actually "install" the game after each GitHub pull? Could it be that you simply have an older version of Terminal Recall which did not have the old-card-fix? The "mvn clean install" is needed after every pull. I had an issue lately that the install was aborted without me noticing it. The console windows always closes automatically so I couldn't read any error messages and so I thought I installed the fixed version but I didn't. 

Just an idea…

**Comment by mrjoshua23** [comment]
yea I run git pull, then i run .\bin\mvn clean install since its in a different directory

**Comment by mrjoshua23** [comment]
ok i get this now!
![image](https://cloud.githubusercontent.com/assets/15824644/11746289/6cc1689c-9feb-11e5-9739-ffd733b4b5ce.png)

pastebin to follow

**Comment by mrjoshua23** [comment]
http://pastebin.com/QSf0r3qv

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11746368/e2de49e6-9feb-11e5-998f-fa4e7ce339b8.png)

![image](https://cloud.githubusercontent.com/assets/15824644/11746371/e87f8f36-9feb-11e5-88f9-e7d262bcab3b.png)

![image](https://cloud.githubusercontent.com/assets/15824644/11746373/ed5c9ea4-9feb-11e5-8328-7b53b5df01ef.png)

**Comment by mrjoshua23** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<java version="1.8.0_60" class="java.beans.XMLDecoder">
 <object class="org.jtrfp.trcl.core.TRConfiguration" id="TRConfiguration0">
  <void property="activeAudioDevice">
   <string>Primary Sound Driver, version Unknown Version</string>
  </void>
  <void property="activeAudioFormat">
   <string>PCM_SIGNED unknown sample rate, 8 bit, stereo, 2 bytes/frame, </string>
  </void>
  <void property="activeAudioOutput">
   <string>interface SourceDataLine supporting 8 audio formats, and buffers of at least 32 bytes</string>
  </void>
  <void property="missionList">
   <void method="clear"/>
   <void method="add">
    <string>FurySE</string>
   </void>
   <void method="add">
    <string>TV</string>
   </void>
   <void method="add">
    <string>Auto-detect</string>
   </void>
   <void method="add">
    <string>Fury3</string>
   </void>
  </void>
 </object>
</java>

settings.config.trcl

**Comment by WDLmaster** [comment]
Yes, that's kinda correct (There should be a background and Title visible, though). Now you just have to add your POD files in the config dialog and after a restart of Terminal Recall you should be able to start a game.

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11759974/f6e1b562-a055-11e5-9bcc-74142a662538.png)

http://pastebin.com/UbM0YXcY

**Comment by cjritola** [comment]
GPU ran out of memory. I need to shrink the memory usage and will check back.

**Comment by mrjoshua23** [comment]
same thing laptop pc btw

**Comment by cjritola** [comment]
Is this with the most recent git pull/build? Yesterday I committed some changes which might have fixed that error.

**Comment by mrjoshua23** [comment]
http://pastebin.com/HECBj8QR

**Comment by cjritola** [comment]
@mrjoshua23 Either your laptop's hardware is not OpenGL 3.3 capable or it doesn't have its graphics drivers properly installed.

**Comment by mrjoshua23** [comment]
yea thanks for reminding me, see its not opengl friendly but it runs windows 10 well

**Comment by mrjoshua23** [comment]
is there a more real-time chat we can use instead of comments?

**Comment by mrjoshua23** [comment]
well this is promising on my gaming pc...
![image](https://cloud.githubusercontent.com/assets/15824644/11858370/eaf1974a-a42e-11e5-9628-87348b28c7f9.png)

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11858378/09413ea8-a42f-11e5-8e3d-8961b903d702.png)

**Comment by mrjoshua23** [comment]
http://pastebin.com/Wq1zHFX7

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11858428/7c60bb98-a42f-11e5-976e-03fc90b83fa1.png)

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11858436/89c4b53c-a42f-11e5-872c-b38ffecc133a.png)

**Comment by mrjoshua23** [comment]
![image](https://cloud.githubusercontent.com/assets/15824644/11858443/9dbb587a-a42f-11e5-9c81-6bcfa4a459d3.png)

**Comment by mrjoshua23** [comment]
aww it looks worse than in dosbox, runs slower too

**Comment by mrjoshua23** [comment]
so disappointed.. on the bright side i know how to use git hub and other stuff to compile more stuff

**Comment by cjritola** [comment]
I am on Google Plus if you want to chat about this there. "Chuck Ritola" same icon.
