### ISSUE TITLE
Crash when no audio plugged in

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#126]
Quoting @WDLMaster:
" The game crashes when no audio cable is plugged in" ... "The log says the complete audio device was not found AKA there are no audio cards available on the system! But this could be a Windows 7 issue because it does not display the actual hardware name but the name of the output port names like "Headphones" or "Stereo-Speakers". And as I see it, TRCL uses the names reported by the system, not the driver."

**Comment by WDLmaster** [comment]
I think you can close this issue because after I did some testing on the older PC in question I see that there's no way for TRCL to tell the difference between a disconnected plug and a not-installed soundcard. The system itself reports the device as non-existent as soon as no cable is plugged in. All other audio applications I tested fail to open the device when no cable is plugged in so this is in no way a TRCL issue.
