### ISSUE TITLE
Malformed tunnels in TV\DESERT.LVL

### ISSUE THREAD

**Issue by cjritola** [jtrfp/terminal-recall#41]
Coordinates to reproduce issue coming soon. The main tunnels are ok, however at least one 'secret' tunnel is grossly deformed and apparently inescapable.

**Comment by cjritola** [comment]
Issue persists.
Possibly related: Part of segment also missing near front of tunnel following rotating 3/4 wall.
![desert-tunnel](https://cloud.githubusercontent.com/assets/1056698/5864303/01f80330-a24f-11e4-881c-98e4ca983778.png)

**Comment by cjritola** [comment]
Correction: The segment is not incomplete but sections so narrowly that backface culling was making it invisible.
![narrow](https://cloud.githubusercontent.com/assets/1056698/5864346/54ef21b8-a24f-11e4-81d0-b61299053edc.png)
That is very, very narrow.

**Comment by WDLmaster** [comment]
That should actually be a quarter cutout.

![](http://www.wdlmaster.de/TRCL/tnl1.jpg)
 If it appears distorted there, it should theoretically distort in other tunnels, too, when cutouts are used. Funny how in the original game, the polygons don't match up. For some odd reason(s), 65536 units do actually NOT equal 360 degrees when it comes to tunnel segments in the original game! It's a little less than 65536. But don't ask me about the actual value. I haven't done in-depth testing.

**Comment by WDLmaster** [comment]
Yep, the problem is with the cutout property of some tunnel segments. ATMOS-T4.LVL placed in ATMOS3.LVL at coords 104,96:
![](http://www.wdlmaster.de/TRCL/tnl2a.jpg)
should look like this:
![](http://www.wdlmaster.de/TRCL/tnl2b.jpg)

And another thing: the 3/4 walls do always rotate in TRCL (?) also in places where they aren't supposed to, like the one above...

**Comment by cjritola** [comment]
I found part of the issue: No cutout handling was implemented. (:
Preceding and following that cutout was obstacle 17, which is defined as a rotating 3/4 wall. Would it be safe to assume that when a segment has cutout active, rotation is disabled for that segment?
Also, the cutout segment apparently shows 100% ambient light. Could this be assumed what -1 for light poly represents? (the doc says 'no light')

**Comment by WDLmaster** [comment]
"Preceding and following that cutout was obstacle 17, which is defined as a rotating 3/4 wall."

Rotating means that this type of obstacle rotates with the segment it's attached to. Other obstacles like the H/V jaws, fan, iris etc. cannot rotate and will always stay aligned no matter what rotation the segments perform. 



"Would it be safe to assume that when a segment has cutout active, rotation is disabled for that segment?"

No, because the behavior of a tunnel segment is in no way influenced by an optional obstacle. The actual obstacle object is just there to cover the empty/backface/clipped area where the pipe changes from 360 to 90 degrees. The half and 3/4 walls are tagged "rotating" because they rotate together with the segment (if rotation is active) they are attached to. This is because you can freely chose on which position your 3/4 pipe should be. 



"Also, the cutout segment apparently shows 100% ambient light."

It has an ambient light of 57344 which is 87,5%. It looks 100% bright because of the dynamic light, which is activated for that segment (light polygon != -1). One thing to note here (which I didn't cover in the Wiki article) is, that the game, because it uses lookup tables (LTE) for light-colors, always saturates lights to max. 100%. It can never get "brighter than bright" so an ambient of 65536 and a dynamic light of 65536 do not add up to appear even brighter than 100%. So a dynamic light has basically no effect when ambient is 100%.


"Could this be assumed what -1 for light poly represents? (the doc says 'no light')"

No, because the polygon light property is only for the dynamic light, which is switched off when that value is -1. The ambient light has ALWAYS an effect. The doc is correct :-)
