### ISSUE TITLE
Will Not Run With Radeon HD xxxx

### ISSUE THREAD

**Issue by stevenstrike** [jtrfp/terminal-recall#56]
Hi Everyone,
I'm having an issue to run Terminal-Recall, when i start the app with : 
java -Dorg.jtrfp.trcl.flow.Game.skipToLevel=EGYPT.LVL -jar RunMe.jar STARTUP.POD FURY3.POD

I got this error on both computers with AMD GPU (one with 7950HD and the other one [laptop] with 4550HD Mobility) : 
Creating GL Texture...
...Done.
...Done.
Vertex shader failed to compile with the following errors:
ERROR: 0:48: error(#132) Syntax error: "f" parse error
ERROR: error(#273) 1 compilation errors. No code generated

Using Java 8 x64 on Windows 8.1 and 7 (Also tried Java 6, 7, x86, JDK editions etc...)
Thanks for reading.

**Comment by cjritola** [comment]
If you're still there, the most recent git appears ready for testing with Radeon HD. On 5570 w/ driver  I can get a playable state; a confirm would be great.

Radeon support is desired - in fact the initial design of the engine was optimized for AMD's use of 128-bit wide memory and it does tend to run faster on AMD cards at the same price point. Over the past year nVIDIA dev was a concentration due to the many people who couldn't get it working w/ GeForce.

As for driver bugs, it's tricky to tell who is at fault sometimes: The GL spec can be quite loose and it is easy to develop on one brand and find it to fail completely on another. I noticed that AMD/ATI drivers tend to be more strict to the spec whereas nVIDIA tends to quietly override the state to make it valid.

AMD/ATI makes serious usage of mapped buffer manual-flushing and implicit synchronization whereas nVIDIA foregoes the flushing process completely. In this case, the AMD/ATI driver is more prone to failure despite the fact that it is the result of following spec more closely. Similar stringency applies to stream-mode of mapped buffers, which will break if misused on AMD/ATI where with nVIDIA things silently go right anyways.

nVIDIA is more stringent about implicit casting to uints than AMD/ATI. Don't know why. Meanwhile, AMD/ATI doesn't tolerate the 'f' suffix for floats whereas nVIDIA does. Linux/intel onboard video driver throws no errors but shows a blank screen.

Another matter found was that I was originally using an nVIDIA quirk where calling uintBitsToFloat was performed to trick the card into accepting single-component integers using GL_FLOAT. This was a workaround to trouble getting RED_INTEGER to work properly in nVIDIA. AMD/ATI properly implements uintBitsToFloat() which undermined my hack to convert the uints to floats - if a denormalized or invalid float is created from the uint bits, the hardware resets the value to zero and throws away the original value. This is actually legitimate behavior as referenced by ARB_shader_precision, under spec 4.0 

(https://www.opengl.org/registry/specs/ARB/shader_precision.txt) "Any denormalized 
    value input into a shader or potentially generated by an operation in a shader 
    can be flushed to 0. "

... from what I see this was left dangling with 3.3, which is what TRCL uses. As a result it has been decided to be avoid it completely and to use floats for indexing, which is discouraged in its own right yet more reliable than the numerically-correct way in this situation. On paper it looks like it can be done so long as one is mindful of the accuracy limits of the IEEE 754 format.

This precipitated a re-design of the depth queue (A-buffer) because of the previous use of uints. There has also been a premature implementation of an experimental idea involving tricking the TMU to perform matrix ops to skip framebuffer->texture passing, which are working on Radeon HD 5570 and nVIDIA GT620. Hopefully this will work out in the real world as well as it does in dev.

There appears to be a quirk in AMD's fragment shader involving uniform arrays where the first element always returns zero which had to be worked around.

On my dev systems, both nVIDIA and AMD/ATI fail to throw errors when the size of a uniform array passed mismatches the size specified in the shader, which breaks spec.

By the time Terminal Recall 1.0 is released, I will have quite a few bugs to proof-case to AMD/nVIDIA, and perhaps when they are fixed, the fixed bugs in the new drivers will break TRCL again and its back to debugging....debugging... debugging...

With this in perspective I feel somewhat sorry for developers of both software and drivers - they are caught in a GPU Tower of Babel scenario and it isn't necessarily all their fault. They could get everything right (or 'wrong' but 'right' in the sense that it works) in development, then months after release a new driver comes out and programs break without anything being done to them. 

People switch video cards and they find some programs are broken and blame the card, not knowing that the program was written against broken drivers and that the card is working fine.

My current fglrx is 14.501.1003
My current nVIDIA is 304.117
Ubuntu
